apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx
data:
  nginx.conf: |
    events {}

    http {
      server {
          listen       80;
          server_name  localhost;

          location / {
              add_header 'Access-Control-Allow-Origin' '*';
              add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
              add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
              
              root   /usr/share/nginx/html;
              index  index.html index.htm;
          }
      }
    }
