###Grafana
grafana:
  defaultDashboardsTimezone: browser
  admin:
    existingSecret: doppler-secret-grafana
    userKey: GRAFANA_ADMIN_USER
    passwordKey: GRAFANA_ADMIN_PASSWORD
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
  additionalDataSources:
    - name: loki
      type: loki
      url: http://loki-gateway.monitoring:80

###Prometheus
defaultRules:
  create: true
kube-state-metrics:
  releaseLabel: true
prometheus:
  retention: 3d
  prometheusSpec:
    additionalScrapeConfigs:
       - job_name: 'kubernetes-metrics'
         kubernetes_sd_configs:
           - role: endpoints
         relabel_configs:
           - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
             action: keep
             regex: metrics-server;https
           - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_namespace]
             action: replace
             target_label: kubernetes_namespace
           - source_labels: [__meta_kubernetes_service_name]
             action: replace
             target_label: kubernetes_name
         metrics_path: /metrics
         scheme: https
         honor_labels: true
         tls_config:
           ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
           insecure_skip_verify: true
         bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
