apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: doppler-secret-app
  namespace: doppler-operator-system
spec:
  tokenSecret: 
    name: doppler-token-secret-app
  managedSecret: 
    name: doppler-secret-app
    namespace: app
---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: doppler-secret-db
  namespace: doppler-operator-system
spec:
  tokenSecret: 
    name: doppler-token-secret-db
  managedSecret: 
    name: doppler-secret-db
    namespace: db
---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: doppler-secret-grafana
  namespace: doppler-operator-system
spec:
  tokenSecret: 
    name: doppler-token-secret-grafana
  managedSecret: 
    name: doppler-secret-grafana
    namespace: monitoring
